# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c4811c258221963e677382bb667ea1d8dc0a816d863c7fa70311162e29fdeb5b6e283615ffdbecedeb9fcd648d915366fb5e3befa2ba9b85f13edc446b137e3c

test:
  secret_key_base: 5f86214a57fde1596da12f6bafdfb89d565b6bfab0575a8ceeb8e58c2a0d5152d71940f32cd77b571b389c471a1cdecef66f9be4a9c7ea84037d6e3fcabd704a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
